#CREAR Y QUITAR LLAVES FORANEAS
#CTRL + ENTER EJECUTAR LO SELECCIONADO
#CTRL+SHIFT+ENTER EJECUTAR TODO
USE GRUPOS;
DESCRIBE ZONAS;
DESCRIBE GRUPO_1;

ALTER TABLE ZONAS
ADD CONSTRAINT
PRIMARY KEY (ID);

CREATE TABLE GRUPO_1
(ID INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(20),
DIR_COD INT NOT NULL
);

ALTER TABLE ZONAS
ADD INDEX IDX_DIRCOD (DIR_COD ASC);

ALTER TABLE GRUPO_1
ADD CONSTRAINT FK_ZONASID
FOREIGN KEY (DIR_COD) REFERENCES ZONAS(ID);



CREATE TABLE GRUPO_2(
ID INT NOT NULL,
NOMBRE VARCHAR(20),
DIR_COD INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(DIR_COD) REFERENCES ZONAS(ID)
);
DESCRIBE GRUPO_2;

ALTER TABLE GRUPO_1
DROP FOREIGN KEY FK_ZONASID;

DESCRIBE GRUPO_1;

#RESTRICCION UNIQUE
ALTER TABLE GRUPO_1
ADD CONSTRAINT U_NOMBRE UNIQUE(NOMBRE);

CREATE TABLE GRUPO_3(
ID INT NOT NULL,
DIR_ID INT NOT NULL,
PRIMARY KEY(ID),
UNIQUE(DIR_ID)
);
DESCRIBE GRUPO_3;

ALTER TABLE GRUPO_1
DROP INDEX U_NOMBRE;
